### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by zinserjan** [zinserjan/mocha-webpack#70]
This project began for me as a prototype with the goal to provide a way to run tests compiled by webpack easily. Just to see if this works I hacked this together and it works pretty well so far - apart from a few issues.

In the last months I thought a lot about some solutions for the outstanding issues and I think it's time to get started.

## Tasks
The following needs to be done before shipping 1.0.0:

### Infrastructure
- [x] ~drop nodejs 0.12 support~ - Done in #72
- [x] ~add [flow](https://flowtype.org/) support~ - Done in #75
- [x] ~add code coverage~ - Done in #74

### Internals
- [x] ~use async/await instead of callback hell~ - Done in #76, #78
- [x] ~refactor/split code into 2 parts:  CLI & API (#65)~ - Done in #78, #88 
- [x] ~replace dynamic entry creation with a static entry file~ - Done in #78
- [x] ~replace the "glob-like" file resolution with [glob](https://github.com/isaacs/node-glob) (#48)~ - Done in #78 
- [x] ~respect defined file extensions in `resolve.extensions` for directory entries (#48)~ - Done in #81
- [x] ~support multiple entry files/patterns/directories (#45, #44)~ - Done in #79
- [x] ~fix: adding / deleting test entry files in watch mode does not trigger a rebuild~ - Done in #93
- [x] ~include [source-map-support](https://github.com/evanw/node-source-map-support) by default~ - Done in #82
- [x] ~write to and read from memory (#25)~ - Done in #83, #86
- [x] ~support custom reporters with relative file paths (#58)~ - Done in #87

### User feedback
- [x] ~ensure order of tasks (compile, test) -> latest log is the relevant one~ - Done in #94
- [x] ~pretty status logging (#60)~ - Done in #97
- [x] ~format webpack errors (strip useless information, make errors more meaningful)~ - Done in #99 
- [ ] provide some kind of verbose mode with useful logging
- [ ] growl should also notify about webpack build status (especially errors)

### Validation
- [ ] warn when a multi compiler config is given (not supported) (#56) 
- [ ] warn and give hint when `--compilers` option is passed in  (#23)
- [ ] warn when CommonsChunkPlugin is used (does not work with node)

### Docs
- [x] ~write docs & provide examples~ - Done in #105

**Comment by zinserjan** [comment]
Just published the first beta release `1.0.0-beta.0`. 

You can install it with `npm install mocha-webpack@next`.

**Comment by martynchamberlin** [comment]
Looking forward to getting this new version on NPM!

**Comment by awexfwex** [comment]
any eta on version 1 being published?

**Comment by zinserjan** [comment]
Just released 1.0.0
